version: '3.8'

services:
  backend:
    build: ./airfood-backend
    ports:
      - "8080:8080"
    volumes:
      - ./airfood-backend/data.json:/app/data.json
    environment:
      - PORT=8080
    restart: always

  frontend:
    build: ./airfood-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
